services:
  app:
    build:
      context: .
      dockerfile: ./infrastructure/DockerFile
    container_name: app
    volumes:
      - ./:/var/www/
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    stdin_open: true
    tty: true
    networks:
      - fastify_proxy
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgresql
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: postgres_password
      POSTGRES_DB: postgres_db
    ports:
      - "5433:5432"
    networks:
      - fastify_proxy

volumes:
  postgres_data:

networks:
  fastify_proxy:
    driver: bridge